### ISSUE TITLE
Sync Failure

### ISSUE THREAD

**Issue by kunall-ll** [cecobask/imdb-trakt-sync#11]
I've updated to the latest and my secrets are correct, but I'm getting this error. I do have tv shows in my watchlist list but that was said to be fixed in a previous version.

```
Run go run cmd/syncer/main.go
{"level":"fatal","ts":"2023-01-[14](https://github.com/kunall-ll/imdb-trakt-sync/actions/runs/3917021448/jobs/6696551623#step:4:15)T05:09:09Z","caller":"syncer/syncer.go:62","msg":"failure initialising imdb client","error":"failure hydrating imdb client: 
failure scraping imdb user id: imdb user id not found: failure scraping imdb response for selector .user-profile.userId and attribute data-
userid","stacktrace":"github.com/cecobask/imdb-trakt-sync/pkg/syncer.NewSyncer\n\t/home/runner/work/imdb-trakt-sync/imdb-trakt-sync/pkg/syncer/syncer.go:62\nmain.main\n\t/home/runner/work/imdb-trakt-sync/imdb-trakt-sync/cmd/syncer/main.go:8\nruntime.main\n\t/opt/hostedtoolcache/go/1.18.9/x64/src/runtime/proc.go:250"}
exit status 1
Error: Process completed with exit code 1.
```

**Comment by cecobask** [comment]
Hi @kunall-ll, the problem here is in the values you've set for the `IMDB_COOKIE_AT_MAIN` and `IMDB_COOKIE_UBID_MAIN` secrets. The cookie values you need are with domain name `.imdb.com`. There could be other cookies with the same name, but different domain name. You can safely ignore any other cookies.

I can assist you with this if you're struggling. I can guarantee this must work for you once you have the correct values for all secrets.

**Comment by kunall-ll** [comment]
Hi, I've triple checked and reset the secrets with the correct` IMDB_COOKIE_AT_MAIN` and `IMDB_COOKIE_UBID_MAIN` secrets. I'm using the domain name .imdb.com but still getting the same error.

**Comment by cecobask** [comment]
Let’s schedule a meeting to investigate this together? I’m in Ireland, the timezone is GMT0. You can send me an email to baskski@gmail.com and we’ll arrange a time slot 👍🏻

**Comment by cecobask** [comment]
After going through this issue with @kunall-ll it was identified that the GitHub repository secrets were not in the correct format.
For anyone facing similar issues, the remedy is to make sure all secrets are present and when filling them out ensure:
- The `Name` field contains just the secret name (example: `SYNC_MODE`)
- The `Secret` field contains just the value of the secret and no extra symbols (example: `dry-run`)

![image](https://user-images.githubusercontent.com/32335835/213516127-1c62ebfb-e229-4c7a-bd49-d275e0f22b1a.png)
