### ISSUE TITLE
Sync two trakt lists

### ISSUE THREAD

**Issue by rfarkv** [cecobask/imdb-trakt-sync#24]
Just an ideia.
Is it possible to implement sync between two trakt lists? The idea is to sync lists between two accounts so we could use it kinda like colab lists.

**Comment by Donostio** [comment]
In the secrets guidance there are notes on entering 'all' for all lists in the appropriate field, or comma seperated names for the lists you want to sync.

**Comment by cecobask** [comment]
Hi @rfarkv, that's an interesting idea!
Feel free to open a pull request with the suggested feature as I won't have time to work on this for now.
