### ISSUE TITLE
Sync is failing

### ISSUE THREAD

**Issue by gadelkareem** [cecobask/imdb-trakt-sync#28]
```go
go build -o build/its main.go
./build/its sync
Error: error creating syncer: failure hydrating trakt client: failure generating auth codes: http request POST https://api.trakt.tv/oauth/device/code returned status code 401: unexpected status code 401
make: *** [Makefile:7: sync] Error 1
Error: Process completed with exit code 2.
```

I see it in your actions log too

**Comment by phyesix** [comment]
![Screenshot 2024-03-27 at 07 58 44](https://github.com/cecobask/imdb-trakt-sync/assets/465801/6e3abd7a-9df2-426a-85a8-69ca336353a9)

The problem persists even though I changed the key a bit ago.

**Comment by cecobask** [comment]
Hi folks, sorry this is happening to you!
I’m currently on a holiday and I won’t be available to investigate the issue until I’m back.
Feel free to poke around if you’re interested in fixing it in the meantime.

**Comment by zoken01** [comment]
Update the code and secrets with latest pull and getting this error as of today:

![image](https://github.com/cecobask/imdb-trakt-sync/assets/36889433/78e08359-d4c9-4a81-95c7-99872bb52c8d)

**Comment by danilvalov** [comment]
The same problem
