### ISSUE TITLE
Error in retrieving IMDB watchlist.

### ISSUE THREAD

**Issue by Valkryst** [cecobask/imdb-trakt-sync#33]
For the last ~15 hours I've noticed most of my `sync` jobs failing with the following error, during the `Sync` step:

```
./build/its sync
Error: error creating syncer: failure hydrating imdb client: failure scraping imdb watchlist id: http request GET https://www.imdb.com/watchlist returned status code 403: unexpected status code 403
make: *** [Makefile:10: sync] Error 1
Error: Process completed with exit code 2.
```

After updating my environment variables, the jobs continued to fail until around ~6 hours ago when one of them succeeded. The subsequent jobs have both failed with the 403 error.

I'm assuming IMDB may have changed something on their end, possibly in an attempt to rate-limit or prevent scraping, and that may be causing a 403 Forbidden error when the script attempts to run.

My only idea for resolving this would be to reduce the interval between runs to every 12-24 hours.

**Comment by Donostio** [comment]
Mine seem to be ok. Just one fail seven hours ago - exit code 2.

**Comment by cecobask** [comment]
Hi folks, this issue is intermittent and I first spotted it about a day or two ago.
I debugged the application locally and got the following output:
```
HTTP/2.0 403 Forbidden
Connection: close
Alt-Svc: h3=":443"; ma=86400
Content-Type: text/html
Date: Tue, 07 May 2024 15:09:39 GMT
Server: Server
Strict-Transport-Security: max-age=47474747; includeSubDomains; preload
Vary: Content-Type,Accept-Encoding,User-Agent
Via: 1.1 8c71fe23914182493dae4cb15c841346.cloudfront.net (CloudFront)
X-Amz-Cf-Id: 4AWuFRwkMn70jCd1R8IE5qXn2hjzmeo_bYIlki6f7je2wXwOlPFTcw==
X-Amz-Cf-Pop: VIE50-P1
X-Amz-Rid: MKPPP8ERFEQHADPJ88BC
X-Cache: Error from cloudfront

<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
</body>
</html>
```

The line `X-Cache: Error from cloudfront` is of particular interest here.
I assume there was a change on the IMDb side, related to their configuration of [AWS CloudFront](https://aws.amazon.com/cloudfront).

If anyone knows how to resolve this issue, all contributions are welcome!

**Comment by Donostio** [comment]
> Mine seem to be ok. Just one fail seven hours ago - exit code 2.

Mine is failing regularly now (has been for a week now) on an intermittent basis.

**Comment by Valkryst** [comment]
Based on my successful/failed syncs, I don't see an obvious pattern to the issue. I just updated my `sync` job to run once every 12h and I'll see if that helps 🤞

**Comment by cecobask** [comment]
I don’t think the success rate would change if you were to decrease the `sync` workflow schedule frequency. When I was debugging the issue locally, I ran the sync 15-20 times in sequence. The success rate was around 40%. My understanding is that IMDb load balances traffic in a specific way. Unfortunately, I couldn’t figure out the pattern that they follow for routing. If someone knowledgeable in this area comes across this issue, I would appreciate any guidance! 👀

**Comment by Donostio** [comment]
It appears to be constantly failing now.

**Comment by cecobask** [comment]
Sorry for the delay in providing a workaround for this.
I identified the root cause and pushed a fix, please sync your forks to avail of it.
The solution was to include a `User-Agent` header in HTTP requests to IMDb.
Additionally, it looks like the HTML content of the watchlist page has changed, so I updated the selector accordingly :+1:

**Comment by rafae667** [comment]
Thanks very much for the fix! Great work.

I noticed that my two custom lists aren't being synced. Before the fix, it was syncing.

**Comment by cecobask** [comment]
> Thanks very much for the fix! Great work.

You're very welcome, @rafae667!

> I noticed that my two custom lists aren't being synced. Before the fix, it was syncing.

There were changes relating to the configuration recently - secrets naming.
Can you please verify if you have a secret called `IMDB_LISTS`? Its value should be comma-separated values (e.g. `ls000000000,ls111111111`)

**Comment by cecobask** [comment]
The above statement assumes you want to sync only the specified IMDb lists.
If you would like to sync all your IMDb lists to Trakt then you don't need to define the `IMDB_LISTS` secret.
There are also some limitations to the number of Trakt lists you can have without a premium account: https://github.com/trakt/api-help/discussions/350

**Comment by rafae667** [comment]
I don't have that secret set, so all lists should sync.
I only have 3 lists in total, the watchlist and 2 custom ones.

I tried with the `IMDB_LISTS ` set and it synced the lists I wanted. Without it, the lists aren't synced.

**Comment by cecobask** [comment]
Thanks for reporting it! I will take a look today

**Comment by cecobask** [comment]
Hi @rafae667, you were right that the sync is no longer working if you don't specify the list identifiers.
After investigating, I discovered that IMDb changed the list page's HTML content and the scraper could no longer identify the list IDs.
I've updated the scraper selectors accordingly and it should be working now!

**Comment by rafae667** [comment]
The IMDB went through some UI changes. I can confirm it's working not without the `IMDB_LISTS`. 
Thank you so much for the quick fix!
