### ISSUE TITLE
Error code 422

### ISSUE THREAD

**Issue by zoken01** [cecobask/imdb-trakt-sync#37]
Hello!

I have been getting this error for a while and couldn't find any fixes.

I updated the code and resubmitted the secrets. I'm getting this error:

`Error: error creating syncer: failure hydrating trakt client: failure simulating trakt device activation form submission: http request POST https://trakt.tv/activate returned status code 422: unexpected status code 422`

![image](https://github.com/cecobask/imdb-trakt-sync/assets/36889433/858ba914-942e-4daa-9994-832db21094e8)
![image](https://github.com/cecobask/imdb-trakt-sync/assets/36889433/a51862c7-8d70-430b-aa72-945a9a9d6047)

Is there anything I might have done wrong?

**Comment by cecobask** [comment]
Hi @zoken01, this looks like a problem with one of the secret values. One of them may contain an invalid character/s.
I recommend double-checking that the values for the Trakt secrets are correctly set.
If the possibility of invalid characters is ruled out, I won't be able to help without knowing your secret values.
Please don't post any of your credentials here as they may be picked up by malicious actors.
Feel free to email them to me at baskski@gmail.com and I can take a look for you. After debugging you can rotate your credentials :+1:

**Comment by zoken01** [comment]
Wow! You can feel the years of debugging ^^ 
I pasted the values of the Trakt secrets in a notepad and there were some inserted spaces.

It now works again flawlessly. 

Thank you immensely for the quick reply and for your work.

Cheers :)

**Comment by cecobask** [comment]
I'm glad I could help you out! I just pushed a permanent fix for this issue now.
From now on spaces will be automatically stripped from secret values.
The only exceptions are the `TRAKT_PASSWORD` and `IMDB_LISTS` values.
