### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BardaktakiAdam** [cecobask/imdb-trakt-sync#38]
Hello, can you please kindly guide me to fix this problem? Thank you

![2024-06-27_9-57-09](https://github.com/cecobask/imdb-trakt-sync/assets/43864069/031b767f-c6fa-4fb1-b90d-777347368a05)

**Comment by cecobask** [comment]
Hi @BardaktakiAdam, I haven't seen this error before.
There is a related issue due to the user interface changes in the IMDb website: https://github.com/cecobask/imdb-trakt-sync/issues/39
Once I get some time over the next few days I will resolve the issues.
Thanks for reporting!

**Comment by BardaktakiAdam** [comment]
> Hi @BardaktakiAdam, I haven't seen this error before. There is a related issue due to the user interface changes in the IMDb website: #39 Once I get some time over the next few days I will resolve the issues. Thanks for reporting!

Thank you so much!

**Comment by BardaktakiAdam** [comment]
Hi, I'm still having this issue. Is there any solution? Thank you

![image](https://github.com/cecobask/imdb-trakt-sync/assets/43864069/ad79ebef-ed85-4867-87d7-70d0ac33265a)
