### ISSUE TITLE
Many empty lists created in Trakt

### ISSUE THREAD

**Issue by aktur** [cecobask/imdb-trakt-sync#50]
Since the last major update with the headless server, it appears that many new lists have been created in Trakt. They all seem to be empty.
<img width="1045" alt="image" src="https://github.com/cecobask/imdb-trakt-sync/assets/5919960/80fae1ad-b8cc-4b55-9987-004f3e7475cc">

**Comment by cecobask** [comment]
My guess is that you included your watchlist ID in the `IMDB_LISTS` secret. This is what can cause such behaviour. The watchlist ID is automatically scraped by the app, there is no need to include it in the secret.

**Comment by aktur** [comment]
When I leave the ids empty then I'm getting this
<img width="950" alt="image" src="https://github.com/cecobask/imdb-trakt-sync/assets/5919960/232cb7a7-d317-4a98-a966-18ad43d4425b">

**Comment by cecobask** [comment]
Right, that I can fix next 👍 This would be an issue when a user doesn’t sync anything else but their watchlist.

**Comment by cecobask** [comment]
Resolved in #52 and #53
