### ISSUE TITLE
Sync Error

### ISSUE THREAD

**Issue by BardaktakiAdam** [cecobask/imdb-trakt-sync#51]
Hello, 

Can you please kindly help me find out a solution for this error? 

Thanks

![image](https://github.com/cecobask/imdb-trakt-sync/assets/43864069/25e17306-659c-4737-9522-8a4cb44cc2d2)

**Comment by cecobask** [comment]
Hi @BardaktakiAdam, your fork of the project is outdated. You need to open [BardaktakiAdam/imdb-trakt-sync](https://github.com/BardaktakiAdam/imdb-trakt-sync) and click `Sync fork`. Keep in mind a lot of things changed in the app lately, so you have go through the [config.yaml](https://github.com/cecobask/imdb-trakt-sync/blob/main/config.yaml), make sure that you have all parameters that you need set as repository secrets and try running the sync workflow again. Let me know if you experience any problems.

**Comment by BardaktakiAdam** [comment]
Thank you for your feedback @cecobask , I have synced the fork, and refreshed the secret keys as you described in the config file. But I am getting this error.

![image](https://github.com/cecobask/imdb-trakt-sync/assets/43864069/483ef645-9a7e-429c-bd1e-5a447208c6f7)

**Comment by BardaktakiAdam** [comment]
I have added it as you want, here is the error log. Thank you

![image](https://github.com/cecobask/imdb-trakt-sync/assets/43864069/bea8476a-b7e5-4763-b874-255aa35d40ae)

**Comment by cecobask** [comment]
Hmm, that didn't help much in figuring out the issue. It could be the network speed at the time.
I've added more bug fixes just now. Please pull the latest changes and try again. I hope it will work out for you then!

**Comment by BardaktakiAdam** [comment]
I have refreshed the fork. And run the actions. Now it gives me this error. Thank you

![image](https://github.com/cecobask/imdb-trakt-sync/assets/43864069/ec59985c-8cd2-45b4-a958-62562238b60d)

**Comment by BardaktakiAdam** [comment]
I have changed the secret such as cookies, now the problem is probably solved. Thanks a lot @cecobask 

![image](https://github.com/cecobask/imdb-trakt-sync/assets/43864069/bdb02087-d1e1-48ce-bdb2-d28b7b317244)

**Comment by cecobask** [comment]
I'm glad I could help you out 🙂 
Keep in mind the sync workflow isn't fully stable right now. Sometimes it will fail and I'm still figuring out some details.
In the meantime, if you observe any failures, feel free to report them by opening a new issue!

**Comment by BardaktakiAdam** [comment]
Yes, as you said after 4 hours I got an error :) But I believe that you will handle this thing tho. Thanks @cecobask 

![image](https://github.com/cecobask/imdb-trakt-sync/assets/43864069/2b682889-4e7a-445b-95d2-c66f082b9fd8)

**Comment by BardaktakiAdam** [comment]
Ohh, when I checked the Trakt.tv, there is a problem with the website. Maybe it's the reason for the error. FYI. Thanks

![image](https://github.com/cecobask/imdb-trakt-sync/assets/43864069/6516d8a1-6f61-4f53-adbe-7a1737c36bb0)
