### ISSUE TITLE
Watchlist sync is creating an additional list

### ISSUE THREAD

**Issue by mxkimball** [cecobask/imdb-trakt-sync#59]
When this action runs, my watchlist updates properly in trakt. But then it also creates an additional list with 0 items. Once I reach my free user limit of 5 custom lists, the script breaks. Happy to provide additional information if necessary. 

![image](https://github.com/user-attachments/assets/2f89a7bb-499a-426f-a0b6-cef03f2fec98)

**Comment by mxkimball** [comment]
found the same issue in a closed issue and was able to troubleshoot. Fix for me was leaving auth as cookies and deleting lists secret.

**Comment by cecobask** [comment]
Hi @mxkimball, this can happen when you’ve included your watchlist ID to the `IMDB_LISTS` secret. There is no need to do that. You can control whether your watchlist syncs with the `SYNC_WATCHLIST` secret - set it to `true` or `false`.
