### ISSUE TITLE
Trakt app error

### ISSUE THREAD

**Issue by paviem** [cecobask/imdb-trakt-sync#60]
Hi
I just started getting the following error a couple of days ago:

Error: error creating syncer: failure initialising trakt client: failure hydrating client: failure simulating trakt api app allowlisting: failure scraping response for selector #desktop-user-avatar and attribute href
make: *** [Makefile:10: sync] Error 1
Error: Process completed with exit code 2.

I've tried creating a new Trakt app/updating client ID and secret but still the same error.

Any help solving this would be much appreciated.

Many thanks,

**Comment by rafae667** [comment]
I can see everyone is getting this error as well, even the main repository

**Comment by cecobask** [comment]
Hi folks, I’m getting the same error. It’s probably a change on the Trakt website. I’ll take a look today or tomorrow when I get a chance 👍

**Comment by cecobask** [comment]
The problem was related to changes in the HTML content on the Trakt website.
I've added a temporary fix to unblock all users of the syncer.
One of the next few days I will implement a more robust way to retrieve the Trakt username via the Trakt API:
```
curl --location 'https://api.trakt.tv/users/me' \
--header 'trakt-api-key: XXX' \
--header 'trakt-api-version: 2' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer XXX'
```
