### ISSUE TITLE
Syncing error happening for the last few weeks

### ISSUE THREAD

**Issue by ashbruh** [cecobask/imdb-trakt-sync#63]
Hello, the workflow stopped working a few weeks ago so i synced the repo and made the changes to the secrets and it was running without errors but no lists were being synced to trakt. For the last few weeks, the workflow keeps failing. I’ve attached a picture of the error below.
![IMG_0934](https://github.com/user-attachments/assets/e62adbdc-c37d-4404-b20b-e346edf7ba7f)

**Comment by cecobask** [comment]
Hi @ashbruh, I identified the reason your sync is failing.
The application didn't prevent you from entering your watchlist ID into the `IMDB_LISTS` configuration option.
This in turn caused some weird behaviour while downloading data from IMDb.
I've addressed this issue. However, the sync workflow is currently broken (#62) for all users and I'm trying to figure out why.
