### ISSUE TITLE
Lists on trakt aren't updating 

### ISSUE THREAD

**Issue by rafae667** [cecobask/imdb-trakt-sync#67]
Hey, just noticed this today. The sync is working without any error and I didn't change my configuration. I noticed that even if I remove or add items on IMDB it won't update on trakt. It was working before.

**Comment by Donostio** [comment]
In case it helps, mine seems to be working fine - I specify each list to sync because I have too many otherwise.

**Comment by cecobask** [comment]
There was a small change on the IMDb website HTML structure. It has been resolved.
Sync your forks and things should be back to normal 🙂

**Comment by rafae667** [comment]
Thank you very much! 🙏
