### ISSUE TITLE
Sync failing

### ISSUE THREAD

**Issue by rafae667** [cecobask/imdb-trakt-sync#7]
Hello,
The repository and many other forks are getting this error while syncing.

![imagem](https://user-images.githubusercontent.com/28830965/207383335-38c2d4d2-a2e6-437c-bf50-39571d3ed3a1.png)

This problem is due to the Trakt website being down.
Anyone with this problem can track the Trakt status on https://status.trakt.tv

**Comment by cecobask** [comment]
The Trakt API and website are back online! 🎉 

https://twitter.com/trakt/status/1605271145086754816?s=46&t=TZZbbxTU3JHoVWnaPS4iVQ
