### ISSUE TITLE
Additional run modes: dry-run & add-only

### ISSUE THREAD

**Issue by McCio** [cecobask/imdb-trakt-sync#9]
I just used this tool to sync imdb ratings to trakt, very useful!
Since I already added something to trakt manually, in the logs it showed some deletions: 1 show from watchlist, and 1 movie and 2 shows from history+ratings.
So I'm thinking two additional run modes would be useful:
* **dry-run**: to see what would be applied, and prevent unwillingly erasing data (I have yet to find which movie and 1 of the show it deleted from history)
* **add-only**: to permit syncing only additions

Also, a log file with all stuff that was executed would be perfect in case some huge erasing happens, in order to be able to revert them (even manually). In the github action you could just `cat` it after run to have it logged.

From my side I plan to only use trakt from now on, so these would be useful additions for others in the future, rather than for me specifically.
Thanks for the effort!

**Comment by cecobask** [comment]
Thanks a lot for the suggestion, @McCio!
I'll be sure to add this functionality soon 🫡
